### PR TITLE
add run cmd

### PR DESCRIPTION
**Pull request by jayantkatia**
## Run Command
Uses [Node-cron](https://www.npmjs.com/package/node-cron) package to schedule [Upptime](https://github.com/upptime/upptime/tree/master/.github/workflows) template's workflows

### CODE REVIEW

**Comment by jayantkatia** [comment]
**Issue::** Verifying SSL Peer certificate raises error for most of the websites.
**Possible Solution::** https://github.com/JCMais/node-libcurl/blob/develop/COMMON_ISSUES.md

**Review by sakshi-choudhary — APPROVED** [review]
LGTM 🚀

**Comment by AnandChowdhary** [comment]
Let's resolve the conflicts and get this merged 😄

**Comment by sakshi-choudhary** [comment]
> Let's resolve the conflicts and get this merged 😄

Yes @jayantkatia is on it.

**Comment by jayantkatia** [comment]
Use
```
path_to_run_binary  run  -ui  number_of_iterations
```

**Pull request merged**
